created button component
sagargse/artzilla pull request #11
Opened 2022-02-09 17:31 UTC by sagargse

created button component

2022-02-09 17:42 UTC, Rockyraven commented on cssfiles/buttons.css
> +}
remove this extra space

2022-02-10 14:16 UTC, sagargse commented on cssfiles/buttons.css
> +}
ok i will

2022-02-10 14:56 UTC, Shailseen approved these changes
looks fine .You can procced to merge.

2022-02-10 14:58 UTC, vishalg8454 requested changes
Just a minor change and all good to merge.

2022-02-10 14:58 UTC, vishalg8454 commented on documentation.html
> +                        <h1>Button</h1>
H1 should remain exclusive for single use in a page. H2 can be used.

2022-02-10 15:02 UTC, sagargse commented on documentation.html
> +                        <h1>Button</h1>
ok will consider that

2022-02-10 15:02 UTC, sagargse commented on documentation.html
> +                        <h1>Button</h1>
ok will consider that

2022-02-10 15:03 UTC, sagargse commented
> looks fine .You can procced to merge.

okay!

2022-02-10 17:12 UTC, merged