created cards component
sagargse/artzilla pull request #12
Opened 2022-02-09 18:39 UTC by sagargse

Created card component

2022-02-09 18:48 UTC, Rockyraven approved these changes
all good for me

2022-02-09 19:15 UTC, pratik-kumar-sahu reviewed
- For "out of stock" card you can disable add to Cart & move to Wishlist buttons

2022-02-09 19:20 UTC, dikshadhote requested changes
The code looks good , just use proper naming convention and px for values below 10px as suggested by vikram.

2022-02-09 19:20 UTC, dikshadhote commented on cssfiles/cards.css
> +    background-color: var(--card-color);
use color name instead of card color

2022-02-09 19:20 UTC, dikshadhote commented on cssfiles/cards.css
> +    border-radius: 0.5rem;
use px for values below 10px

2022-02-09 19:20 UTC, dikshadhote commented on cssfiles/cards.css
> +    border-top-right-radius: 0.5rem;
same as mentioned above

2022-02-09 19:20 UTC, dikshadhote commented on cssfiles/cards.css
> +    margin: 0.5rem;
same as above

2022-02-09 19:20 UTC, dikshadhote commented on cssfiles/cards.css
> +    border-radius: 0.5rem;
same as above

2022-02-09 19:20 UTC, dikshadhote commented on cssfiles/cards.css
> +    background-color: var(--btn-hover);
use color names, btn-hover doesn't gives idea about color you are using

2022-02-09 19:20 UTC, dikshadhote commented on cssfiles/cards.css
> +    border-radius: 0.5rem;
same as above

2022-02-09 19:20 UTC, dikshadhote commented on cssfiles/cards.css
> +    background-color: var(--btn-hover);
same as above

2022-02-09 19:20 UTC, dikshadhote commented on cssfiles/cards.css
> +    border-radius: 0.5rem;
same as above

2022-02-09 19:20 UTC, dikshadhote commented on cssfiles/cards.css
> +    border-radius: 0.5rem;
same as above

2022-02-09 19:20 UTC, dikshadhote commented on cssfiles/cards.css
> +    border-bottom-left-radius: 0.5rem;
same as above

2022-02-09 19:20 UTC, dikshadhote commented on cssfiles/cards.css
> +    padding: 0.5rem;
same as above

2022-02-09 19:20 UTC, dikshadhote commented on main.css
> +    --card-color:#d3d3d3ee;
use color names as you have used for light gray

2022-02-10 17:19 UTC, sagargse commented
> * For "out of stock" card you can disable add to Cart & move to Wishlist buttons

ok i will do that

2022-02-10 17:19 UTC, sagargse commented on main.css
> +    --card-color:#d3d3d3ee;
okay will correct that

2022-02-10 17:20 UTC, sagargse commented on cssfiles/cards.css
> +    border-radius: 0.5rem;
okay!

2022-02-10 17:20 UTC, sagargse commented on cssfiles/cards.css
> +    background-color: var(--card-color);
okay!

2022-02-10 17:49 UTC, merged